server:
  port: 8888

spring:
  servlet:
    multipart:
      #單個文件最大容量
      max-file-size: 10MB
      #一次性上傳文件最大容量
      max-request-size: 50MB


  datasource:
    url: jdbc:mysql://localhost:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hsp
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.msh.springboot.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

